// 全站搜索数据：每个功能的完整介绍 + 搜索关键词（中英/同义词/俗写）。
// 由 components/search.js 的命令面板消费；关键词越全，搜索命中率越高。
export const SEARCH_INTROS = {
  merge: '把多个 PDF 与图片按任意顺序合并成一个文件；每个 PDF 可单独指定参与合并的页范围，顺序可拖拽调整。',
  split: '把一份 PDF 拆分为多个文件：按每 N 页一份、固定页范围或自定义区间，输出 ZIP 或多个 PDF。',
  organize: '缩略图工作台直观整理页面：拖拽重排顺序、旋转、删除、复制、插入空白页，所见即所得。',
  edit: '在 PDF 页面上添加文字、图片、高亮、矩形/椭圆等标注，可移动、缩放、删除，导出为真实可编辑内容的 PDF。',
  watermark: '为 PDF 添加文字或图片水印：九宫格锚点/拖动定位、平铺/对角线/全屏铺满、透明度、旋转、页范围，带实时预览。',
  overlay: '把一份 PDF（如信纸、盖章页）叠加到另一份上：可控制缩放、位置、透明度与前后层关系。',
  compress: '智能压缩 PDF 体积：图像重压缩、整页栅格化、结构无损三种模式自动寻优，附 SSIM 质量评估保证观感。',
  security: '为 PDF 设置或移除打开密码与权限密码（AES-256 高强度加密），错误密码有明确提示。',
  office: '在浏览器本地把 .docx/.pptx 近似转换为 PDF（ mammoth 解析+排版重建），复杂版式可能有偏差。',
  ocr: '扫描件/图片型 PDF 识别为可搜索的 PDF 与纯文本，支持简体、繁体、英文等多种语言，可调识别 DPI。',
  text: '提取 PDF 原生文字层为 .txt，按页输出、保留阅读顺序；扫描件（无文字层）请先用 OCR。',
  images2pdf: '把多张图片合成为 PDF：可排序、选择纸张/边距/适应方式，自动识别 EXIF 旋转方向。',
  pdf2images: '把 PDF 每页导出为 PNG/JPEG 图片：可选页范围、DPI（72-600）与质量，支持长图拼接。',
  extractimages: '提取 PDF 内嵌的原始图像文件：区分「原图提取」（无损）与「页面渲染」两种模式。',
  compare: '对比两份 PDF：像素级差异热图 + 文本逐行差异（类 git diff）双视图，并排展示、差异高亮、联动缩放。',
  rotate: '按页范围旋转 PDF 页面 90/180/270°，支持相对追加或绝对设定，横竖页混排场景友好。',
  removepages: '按页码/范围/奇偶页删除 PDF 中的指定页面，快速瘦身文档。',
  extractpages: '从 PDF 中抽取选定的页面另存为新文件，配合页范围语法（如 1-3,7,10-）。',
  nup: '多页拼版到一张纸：2 合 1、4 合 1、6 合 1、9 合 1、16 合 1，可加分割线，适合打印讲义。',
  halve: '把每一页裁切为左右两半或上下两半，常用于横版双栏扫描件、PPT 讲义还原。',
  crop: '按边距/百分比/精确框设置裁剪区域，去掉扫描白边或多余留白，可全局或按页设置。',
  resize: '把所有页面统一调整为 A4/A3/A5/Letter 等标准规格，可选缩放或留白适应。',
  bookmarks: '为 PDF 写入大纲书签（标题/目标页码/层级），在阅读器侧边栏显示目录树。',
  docinfo: '查看并编辑 PDF 元数据：标题、作者、主题、关键词、创建/修改时间等。',
  metaclean: '一键清空文档信息与 XMP 元数据，去除作者、软件、轨迹等隐私痕迹。',
  viewerpref: '设置 PDF 打开方式偏好：单页/双页/书签视图、全屏模式、隐藏工具栏等 Catalog 标记。',
  createpdf: '富文本撰写器：设置标题/列表/表格后导出为排版 PDF，适合快速出稿。',
  txtpdf: '把 .txt/.csv 文本文件按字号、页边距、行距排版为 PDF，支持自动分页。',
  md2pdf: 'Markdown 在线编辑器：左侧编辑右侧实时预览，导出 PDF（内置/Typst/打印多引擎）或 Word(.docx)；支持公式、Mermaid、思维导图、代码高亮。',
  rtf2pdf: 'RTF 富文本文档转换为 PDF，保留字体、加粗、颜色等基本格式。',
  epub2pdf: 'EPUB 电子书按章节转换为 PDF，适合打印与批注。',
  odf2pdf: 'OpenDocument 文档（odt/ods/odp/odg）转换为 PDF。',
  excelpdf: 'xlsx 表格转换为 PDF，每张工作表一节，保留数值格式；旧 .xls 不支持。',
  svgpdf: 'SVG 矢量图转换为 PDF，可设置页面尺寸与边距。',
  tiffpdf: '多页 TIFF 图像文件转换为 PDF，每页一帧不丢页。',
  heicpdf: 'iPhone/iPad 的 HEIC 照片转换为 PDF，自动处理方向。',
  webpage: '粘贴 HTML 源码、输入网址或上传 .html 文件，一键导出 HTML 文件与 PDF：内置引擎生成可选中文字、浏览打印引擎保真原样式（受 CORS 限制，部分站点需粘贴源码或上传文件）。',
  scan: '调用摄像头连续拍摄纸质文件，自动合成多页 PDF，即拍即存。',
  qrcode: '把文本/网址生成二维码 PNG，可调整尺寸与纠错级别，也能直接嵌入 PDF。',
  passgen: '纯本地生成高强度随机密码：可指定长度、字符集（大小写/数字/符号），绝不联网。',
  invoice: '填写发票抬头、条目与金额，生成规范的 PDF 单据。',
  webpconvert: '批量把 WebP 图像转换为 JPG/PNG，Chrome 保存的 WebP 素材一键转通用格式。',
  heicconvert: '把 iPhone 的 HEIC/HEIF 照片批量转换为 JPG/PNG，自动纠正方向。',
  sign: '手绘或输入签名，盖章到 PDF 任意位置：可缩放、透明，适合合同快速签署。',
  redact: '涂抹标记敏感区域后物理删除下层文字与图像，不是黑框遮盖，杜绝恢复泄露。',
  formfill: '自动识别 PDF 内的 AcroForm 表单字段（文本框/复选框），填写后可扁平化锁定。',
  formcreate: '在 PDF 上添加可填写的文本框、复选框等表单字段，制作交互式表单。',
  pagenumbers: '为 PDF 添加页码：九宫格位置、格式模板（第 X 页/共 Y 页）、起始编号，CJK 字体安全不乱码。',
  flatten: '扁平化 PDF：把表单字段/注释烧入页面内容，或整册栅格化，防止后续篡改。',
  rasterize: '把整册 PDF 按指定 DPI 转为图像型 PDF，文字不再可选中，用于防编辑或统一显示。',
  repair: '修复损坏的 PDF：重建交叉引用表与文件结构，尽量抢救可读内容。',
  viewer: '本地 PDF 阅读器：连续翻页、缩放、旋转，完全离线浏览文档。',
  search: '在整份 PDF 中搜索关键词，列出命中页码与上下文，点击跳转。',
  pdf2word: 'PDF 转 Word(.docx)：保留段落与标题层级，文本级转换（不还原原始排版）。',
  pdf2ppt: 'PDF 转 PPT：每页作为一帧幻灯片，文本级转换生成可编辑文本框。',
  pdf2pptimg: 'PDF 转图片型 PPT：每页渲染为高清图片、整幅铺满一帧，观感与原 PDF 完全一致。',
  pdf2excel: 'PDF 转 Excel(.xlsx)：每页一张工作表，按行拆分单元格，文本级转换。',
  pdf2html: 'PDF 转单文件 HTML：标题分级为 h1-h3，保留段落结构，离线可看。',
  pdf2md: 'PDF 转 Markdown(.md)：标题映射 #/##/###，保留列表与段落，方便入库。',
  pdf2rtf: 'PDF 转 RTF 富文本，各大文字处理器均可打开。',
  pdf2epub: 'PDF 转 EPUB 电子书，每页一章，适合阅读器。',
  pdf2odf: 'PDF 转 OpenDocument（ODT/ODS/ODP），接入 LibreOffice 生态。',
  pdf2tiff: 'PDF 转多页 TIFF，Pillow/预览器可直接读取，适合档案系统。',
  pdf2svg: 'PDF 每页导出为 SVG（位图封装，非矢量追踪），可嵌入网页。',
};

export const SEARCH_KEYWORDS = {
  merge: ['合并', '拼接', 'join', 'combine', 'concat', 'merge pdf', '多个文件', '合成', '拼成一个', '添加页面', '组合'],
  split: ['拆分', '切开', '分开', 'split', '一分为多', '按页拆', '切割', '分成多个', '分割'],
  organize: ['整理', '重排', '排序', '拖拽', 'organize', '缩略图', '调整顺序', '页面顺序', '拖动', '移动页面', '复制页', '删页', '旋转页'],
  edit: ['编辑', '标注', '批注', '加文字', '加图片', '高亮', 'edit', '注释', '画框', '箭头', '修改内容', '写字'],
  watermark: ['水印', 'watermark', 'logo', '盖章', '平铺水印', '文字水印', '图片水印', '密水印', '斜水印', '版权', '防伪'],
  overlay: ['叠加', '盖章页', 'overlay', '套打', '信纸', '衬底', '图层', '垫底', '覆盖', '水印页叠加'],
  compress: ['压缩', 'compress', '变小', '减小体积', '优化', '瘦身', '文件太大', '压缩质量', '智能压缩', 'shrink', '体积'],
  security: ['密码', '加密', 'encrypt', 'password', '保护', '解锁', '解密', '权限', 'aes', '去掉密码', '打开密码', '只读'],
  office: ['word转pdf', 'ppt转pdf', 'docx', 'pptx', 'office', '文档转pdf', 'mammoth', '办公'],
  ocr: ['ocr', '识别', '文字识别', '扫描件', ' searchable', '可搜索', '图片转文字', 'tesseract', '中英识别', '图文转换'],
  text: ['提取文本', '文字提取', 'text', '拷贝文字', '导出txt', '抓取文字', '纯文本', '文本层'],
  images2pdf: ['图片转pdf', 'images to pdf', '照片合成', 'jpg转pdf', 'png转pdf', '多图合并', '相册', '图片打包'],
  pdf2images: ['pdf转图片', '转png', '转jpg', '导出图片', 'render', '截页', '页面转图', '长图', '高清导出'],
  extractimages: ['提取图片', '内嵌图像', '原图', 'extract images', '抠图', '导出素材', '拿图片'],
  compare: ['比较', '对比', 'compare', 'diff', '差异', '版本对比', '改动对照', '像素对比', '找不同'],
  rotate: ['旋转', 'rotate', '转90度', '横竖转换', '躺倒', '方向', '竖版转横版'],
  removepages: ['删除页面', 'remove', '去掉页', '删页', '减页', '移除页', '丢弃页面'],
  extractpages: ['提取页面', '抽取', 'extract', '选页导出', '保留某些页', '截取页'],
  nup: ['拼版', 'n-up', '多合一', '2合1', '4合1', '9合1', '16合1', '打印讲义', '每页页数', '缩小打印'],
  halve: ['切半', '一分为二', '对半', 'halve', '双栏还原', '扫描切分', '左右分开'],
  crop: ['裁剪', 'crop', '裁切', '去白边', '裁边', '剪裁', '框选区域', '去黑边'],
  resize: ['页面大小', 'resize', '改尺寸', 'a4', 'a3', 'letter', '统一尺寸', '规格', '比例调整'],
  bookmarks: ['书签', '目录', 'outline', '大纲', 'bookmark', '导航目录', '添加目录', 'toc'],
  docinfo: ['文档信息', '元数据', 'metadata', '属性', '作者', '标题修改', 'docinfo', '查看信息', '编辑属性'],
  metaclean: ['移除元数据', '隐私', '清空信息', 'metaclean', '去痕迹', '匿名', 'xmp', '删除作者'],
  viewerpref: ['查看器', '打开方式', '阅读偏好', 'viewer', '双页显示', '全屏', '隐藏工具栏', 'catalog'],
  createpdf: ['生成pdf', '新建pdf', '写文章', '富文本', 'create', '撰写', '空白文档', '出稿'],
  txtpdf: ['文本转pdf', 'txt转pdf', 'csv', '排版', '记事本转', '文字文件'],
  md2pdf: ['markdown', 'md', 'md转pdf', 'md转word', 'typst', 'pandoc', '公式', 'mermaid', '思维导图', '代码高亮', '编辑器', '实时预览', 'docx导出'],
  rtf2pdf: ['rtf', 'rtf转pdf', '富文本转换', 'wordpad', 'rtf文档', '写字板', 'rich text', 'rtf文件转换'],
  epub2pdf: ['epub', '电子书', 'epub转pdf', '书', '章节', 'epub文件', 'kindle', '电子书转换'],
  odf2pdf: ['odf', 'odt', 'ods', 'odp', 'libreoffice', 'open document', 'odg', 'openoffice'],
  excelpdf: ['excel转pdf', 'xlsx', '表格转pdf', '电子表格', '工作表', 'excel文件', '表格导出', 'sheet转pdf'],
  svgpdf: ['svg', 'svg转pdf', '矢量图', 'vector', 'svg文件', '矢量转换'],
  tiffpdf: ['tiff', 'tif', 'tiff转pdf', '多页tiff', '传真', 'tif转pdf', 'tiff文件'],
  heicpdf: ['heic', 'heif', '苹果照片', 'iphone', 'heic转pdf', 'ios照片'],
  webpage: ['网页转pdf', 'html转pdf', 'html代码转pdf', 'url', '网址', '截取网页', 'web', '打印网页', 'html文件', '保存网页', '保存网页为pdf', '网页快照', '网页存档', '源码转pdf', '代码转pdf', '链接转pdf', 'html转文件'],
  scan: ['扫描', '拍照', '摄像头', 'scan', '相机', '纸质文件', '连拍'],
  qrcode: ['二维码', 'qrcode', 'qr', '生成码', '扫码', '网址转码', '二维码生成', 'qr码'],
  passgen: ['密码生成', '随机密码', 'password generator', '强密码', '随机串', '安全密码', '随机生成'],
  invoice: ['发票', 'invoice', '单据', '收据', '票据', 'billing'],
  webpconvert: ['webp', 'webp转jpg', 'webp转png', '格式转换', '图片格式', 'convert'],
  heicconvert: ['heic转jpg', 'heif', '图片转换', '苹果照片转换', 'ios', '格式转换'],
  sign: ['签名', '签字', '签署', 'sign', 'signature', '手写', '盖章', '合同签署'],
  redact: ['涂黑', '遮盖', 'redact', '敏感信息', '脱敏', '保密', '打码', '涂抹', '删除敏感'],
  formfill: ['填表', '表单', 'form', 'acroform', '填写pdf', '文本框填写', '表单字段'],
  formcreate: ['创建表单', '可填写', 'form create', '交互表单', '加文本框', '复选框表单'],
  pagenumbers: ['页码', '加页码', 'page number', '编号', '第几页', '页脚', '页眉'],
  flatten: ['扁平化', 'flatten', '烧入', '不可编辑', '锁定', '表单固化', '注释固化'],
  rasterize: ['栅格化', 'rasterize', '转图片pdf', '不可复制', '位图化', '防编辑'],
  repair: ['修复', 'repair', '损坏', '打不开', '救回来', '重建', 'recover', '坏文件'],
  viewer: ['查看', '阅读', '浏览', 'viewer', 'reader', '看pdf', '打开pdf', '预览'],
  search: ['搜索', '查找', 'search', 'find', '找文字', '全文检索', '关键词定位'],
  pdf2word: ['pdf转word', 'pdf to docx', '转docx', '可编辑word', '导出word', 'pdf转文档'],
  pdf2ppt: ['pdf转ppt', 'pdf to pptx', '幻灯片', 'slides', '演示文稿', 'ppt导出', '转演示文稿', '每页一帧'],
  pdf2pptimg: ['pdf转ppt', '图片型ppt', '每页一帧', 'pptx图片', '版式一致', '高清幻灯片', 'pdf to ppt image'],
  pdf2excel: ['pdf转excel', 'pdf to xlsx', '表格提取', 'xlsx导出', '工作表', 'excel导出'],
  pdf2html: ['pdf转html', '网页格式', '单文件html', 'pdf to html', '浏览器可看', 'html导出'],
  pdf2md: ['pdf转markdown', 'pdf to md', '转md', '笔记', '入库', 'md导出', 'markdown文件'],
  pdf2rtf: ['pdf转rtf', '富文本导出', 'pdf to rtf', 'rtf文档', '写字板格式', 'rtf导出', 'rich text', '通用富文本'],
  pdf2epub: ['pdf转epub', '电子书导出', 'pdf to epub', '阅读器格式', 'epub导出', '电子书格式', '章节', '阅读器'],
  pdf2odf: ['pdf转odf', 'pdf转odt', 'open document', 'libreoffice', 'odf导出', 'odt导出', 'odp', 'openoffice'],
  pdf2tiff: ['pdf转tiff', '多页tiff导出', 'pdf to tiff', '档案格式', 'tif导出', 'tiff文件', '传真格式', '多页tif'],
  pdf2svg: ['pdf转svg', '矢量导出', 'pdf to svg', '嵌入网页', 'svg文件', 'svg导出', '网页图形', '每页svg'],
};
